name: "Check for releases"
on:
  # schedule:
  #   - cron: '*/30 * * * *'
  push: # For testing only
  workflow_dispatch: # For testing only

jobs:
  release-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          path: docs
          ref: automatic-pr-generator #for testing only

      - name: Clone go-algorand repo
        uses: actions/checkout@v3
        with:
          repository: algorand/go-algorand
          ref: rel/stable
          path: go-algorand

      - name: Clone Indexer repo
        uses: actions/checkout@v3
        with:
          repository: algorand/indexer
          ref: master
          path: indexer

      - name: Get current documentation versions
        id: current_versions
        run: |
          cd docs
          TEMP_STABLE=$(cat .go-algorand-stable.version)
          echo "Stable version: $TEMP_STABLE"
          echo "::set-output name=stable::$TEMP_STABLE"
          TEMP_BETA=$(cat .go-algorand-beta.version)
          echo "Beta version: $TEMP_BETA"
          echo "::set-output name=beta::$TEMP_BETA"
          TEMP_INDEXER=$(cat .indexer.version)
          echo "Indexer version: $TEMP_INDEXER"
          echo "::set-output name=indexer::$TEMP_INDEXER"

      - name: Get latest stable and beta go-algorand releases
        id: latest_go_algorand
        run: |
          cd go-algorand
          git fetch --tags
          echo "::set-output name=stable::$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*-stable' | sort -V | tail -1)"
          git tag --list 'v[0-9]*.[0-9]*.[0-9]*-stable' | sort -V | tail -1
          echo "::set-output name=beta::$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*-beta' | sort -V | tail -1)"
          git tag --list 'v[0-9]*.[0-9]*.[0-9]*-beta' | sort -V | tail -1

      - name: Get latest indexer release without dashes
        id: latest_indexer
        run: |
          cd indexer
          git fetch --tags
          echo "::set-output name=indexer::$(git tag --list '[0-9]*.[0-9]*.[0-9]*' | grep -v '-' | sort -V | tail -1)"
          git tag --list '[0-9]*.[0-9]*.[0-9]*' | grep -v '-' | sort -V | tail -1

    outputs: # Translate step outputs into job outputs
      current_stable: ${{ steps.current_versions.outputs.stable }}
      current_beta: ${{ steps.current_versions.outputs.beta }}
      current_indexer: ${{ steps.current_versions.outputs.indexer }}
      latest_stable: ${{ steps.latest_go_algorand.outputs.stable }}
      latest_beta: ${{ steps.latest_go_algorand.outputs.beta }}
      latest_indexer: ${{ steps.latest_indexer.outputs.indexer }}

  version-test:
    name: Testing versions match
    needs: release-checker
    runs-on: ubuntu-latest
    steps:
      - name: check versions
        run: |
          echo "Checking if current stable: ${{ needs.release-checker.outputs.current_stable }} equals latest stable: ${{ needs.release-checker.outputs.latest_stable }}"
          [[ "${{ needs.release-checker.outputs.current_stable }}" == "${{ needs.release-checker.outputs.latest_stable }}" ]] && echo "Matches" || echo "NO MATCH!!"
          echo "Checking if current beta: ${{ needs.release-checker.outputs.current_beta }} equals latest beta: ${{ needs.release-checker.outputs.latest_beta }}"
          [[ "${{ needs.release-checker.outputs.current_beta }}" == "${{ needs.release-checker.outputs.latest_beta }}" ]] && echo "Matches" || echo "NO MATCH!!"
          echo "Checking if current indexer: ${{ needs.release-checker.outputs.current_indexer }} equals latest indexer: ${{ needs.release-checker.outputs.latest_indexer }}"
          [[ "${{ needs.release-checker.outputs.current_indexer }}" == "${{ needs.release-checker.outputs.latest_indexer }}" ]] && echo "Matches" || echo "NO MATCH!!"


  trigger-pr-generator-stable:
    name: Trigger docs and version updates if STABLE versions don't match
    needs: release-checker
    if: |
      needs.release-checker.outputs.current_stable != needs.release-checker.outputs.latest_stable ||
      needs.release-checker.outputs.current_indexer != needs.release-checker.outputs.latest_indexer
    uses: algorand/docs/.github/workflows/pr-generator.yml@automatic-pr-generator
    with:
      go_algorand_version: ${{ needs.release-checker.outputs.latest_stable }}
      indexer_version: ${{ needs.release-checker.outputs.latest_indexer }}

  trigger-pr-generator-beta:
    name: Trigger docs and version updates if BETA versions don't match
    needs: release-checker
    if: needs.release-checker.outputs.current_beta != needs.release-checker.outputs.latest_beta
    uses: algorand/docs/.github/workflows/pr-generator.yml@automatic-pr-generator
    with:
      go_algorand_version: ${{ needs.release-checker.outputs.latest_beta }}
      indexer_version: ${{ needs.release-checker.outputs.latest_indexer }}
